version: '3.7'
services:
  mysqldb:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./src/test/resources:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
